FROM node:16.13

ARG WORKSPACE
ENV WORKSPACE=$WORKSPACE

WORKDIR /usr/src

COPY . .

RUN npm i -g yarn --force

RUN yarn install --frozen-lockfile

ENV NODE_PATH=/usr/src/node_modules

CMD yarn workspace ${WORKSPACE} dev