version: "3"

services:
  db:
    image: postgres:13
    container_name: ${DB_CONTAINER_NAME}
    hostname: ${DB_CONTAINER_NAME}
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d

  server:
    container_name: ${SERVER_CONTAINER_NAME}
    hostname: ${SERVER_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile_${DOCKER_ENV}
      args:
        - WORKSPACE=server
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped
    environment:
      - PORT=${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
      - /usr/src/server/node_modules
      - /usr/src/server/dist

  client:
    container_name: ${CLIENT_CONTAINER_NAME}
    hostname: ${CLIENT_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile_${DOCKER_ENV}
      args:
        - WORKSPACE=client
    depends_on:
      - db
      - server
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${CLIENT_PORT}
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
      - /usr/src/client/node_modules
      - /usr/src/client/.next

volumes:
  database:
    driver: local
