version: '3'

services:
  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 25432:5432
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile_${DOCKER_ENV}
      args:
        - WORKSPACE=server
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - PORT=${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
      - /usr/src/server/node_modules
      - /usr/src/server/dist

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./Dockerfile_${DOCKER_ENV}
      args:
        - WORKSPACE=client
    depends_on:
      - db
      - server
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=${CLIENT_PORT}
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
      - /usr/src/client/node_modules
      - /usr/src/client/.next

volumes:
  database:
    driver: local
