FROM node:16.14-slim

RUN apt-get update
RUN apt-get install -y openssl

WORKDIR /usr/src

COPY . .

RUN npm i -g yarn --force

RUN yarn install --frozen-lockfile

ENV NODE_PATH=/usr/src/node_modules

RUN yarn workspace ${WORKSPACE} build

CMD yarn workspace ${WORKSPACE} start